name: or_en_pepite
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  audioplayers: ^3.0.1
  auto_route: ^5.0.4
  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.1
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  # flutter_facebook_auth: ^5.0.7
  # flutter_local_notifications: ^8.2.0
  # font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.0
  path: ^1.8.2
  path_provider: ^2.0.13
  # permission_handler: ^10.2.0
  # sqflite: ^2.2.4+1
  # uuid: ^3.0.7
  video_player: ^2.5.1
  youtube_explode_dart: ^1.12.3
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.12.0"

flutter_icons:
  image_path: "assets/logos/app.png"
  ios: true
  android: true




flutter:
  uses-material-design: true
  assets:
    - assets/logos/google_light.png
    - assets/logos/google_dark.png
    - assets/logos/facebook_new.png
    - assets/images/

