// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0BxJBi8Fz0r322_C4qHp0SgJqnpU2YpE',
    appId: '1:766139655028:web:1bf94a04b34b561c378221',
    messagingSenderId: '766139655028',
    projectId: 'or-en-pepite',
    authDomain: 'or-en-pepite.firebaseapp.com',
    storageBucket: 'or-en-pepite.appspot.com',
    measurementId: 'G-50H6BWSXGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAJgfmILDfrNGxaR8Pcbu3CipJ0Rm4Uo',
    appId: '1:766139655028:android:99852967bbfa8a3c378221',
    messagingSenderId: '766139655028',
    projectId: 'or-en-pepite',
    storageBucket: 'or-en-pepite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDK9cbmdcbnlU9frPNQjNd8FZmWRUldR8',
    appId: '1:766139655028:ios:4ef0e56429b97634378221',
    messagingSenderId: '766139655028',
    projectId: 'or-en-pepite',
    storageBucket: 'or-en-pepite.appspot.com',
    androidClientId: '766139655028-4jcsh29c8dh1p2gokt4heabljlhrtvaq.apps.googleusercontent.com',
    iosClientId: '766139655028-re8mdnekk9t5klj03rcj4dp77fnolj8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.orEnPepite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDK9cbmdcbnlU9frPNQjNd8FZmWRUldR8',
    appId: '1:766139655028:ios:4ef0e56429b97634378221',
    messagingSenderId: '766139655028',
    projectId: 'or-en-pepite',
    storageBucket: 'or-en-pepite.appspot.com',
    androidClientId: '766139655028-4jcsh29c8dh1p2gokt4heabljlhrtvaq.apps.googleusercontent.com',
    iosClientId: '766139655028-re8mdnekk9t5klj03rcj4dp77fnolj8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.orEnPepite',
  );
}
